id: "bolt_exec_bolt"
version: "1.0.2"
title: "bolt_exec_puppet (Install)"
authors: "patrick"
owners: "patrick"
requireLicenseAcceptance: "false"
description: "bolt_exec_puppet go binary for using puppet via bolt"
summary: "Installiert bolt_exec_puppet unter Windows"
tags: "bolt_exec_puppet go golang"